name: ecom
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.4
  cupertino_icons: ^1.0.0
  enum_to_string: ^1.0.14
  firebase_auth: ^0.18.4+1
  firebase_core: ^0.5.3
  firebase_storage: ^5.2.0
  flutter_launcher_icons: ^0.8.1
  flutter_rating_bar: ^3.2.0+1
  flutter_svg:
  flutter_tags: ^0.4.9+1
  future_progress_dialog: ^0.1.1
  image_picker: ^0.6.7+15
  intl: ^0.16.1
  logger: ^0.9.4
  getwidget: ^1.2.4
  fancy_shimmer_image: ^1.2.0
  permission_handler: ^5.0.1+1
  #  pinch_zoom_image_updated: ^0.2.6
  provider: ^4.3.2+3
  string_validator: ^0.1.4
  swipedetector: ^1.2.0
  url_launcher: ^5.7.10
  intro_slider: ^2.3.3
  google_sign_in: ^4.5.9

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/launcher_icon_with_bg.png"


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - illustrations/
    - assets/icons/
    - assets/icons/User.png
  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-Light.ttf
          weight: 300
